basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a demo API to ICMP-ping an IP address.
  title: Simple ICMP Ping API
  version: "1.0"
paths:
  /ping:
    get:
      description: Sends an ICMP Echo Request to the given IP address
      parameters:
      - description: IP Address
        in: query
        name: ip
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Missing IP
          schema:
            type: string
      summary: Ping an IP address via ICMP
swagger: "2.0"
